name: OWRT-T1  #CI项目名

on:
  workflow_dispatch:  #手动编译

permissions: write-all

jobs:
  owrt_build:
    uses: ./.github/workflows/OWRT-TC.yml
    with:
      OWRT_TARGET: Rockchip  #项目平台
      OWRT_THEME: argon  #默认主题
      OWRT_NAME: IWRT  #默认主机名
      OWRT_PW: password  #默认密码，仅作展示，请勿修改
      OWRT_IP: 192.168.2.1  #默认IP地址
      OWRT_URL: https://github.com/immortalwrt/immortalwrt.git
    secrets:
      TOKEN: ${{secrets.GITHUB_TOKEN}}
