name: OWRT-TC  #云编译公用核心

on:
  workflow_call:  #公用核心标识
    inputs:
      OWRT_TARGET:
        required: true
        type: string
      OWRT_THEME:
        required: true
        type: string
      OWRT_NAME:
        required: true
        type: string
      OWRT_PW:
        required: true
        type: string
      OWRT_IP:
        required: true
        type: string
      OWRT_URL:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  owrt_core:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "${{inputs.OWRT_TARGET}}"
          echo "${{inputs.OWRT_THEME}}"
          echo "${{inputs.OWRT_NAME}}"
          echo "${{inputs.OWRT_PW}}"
          echo "${{inputs.OWRT_IP}}"
          echo "${{inputs.OWRT_URL}}"

      - name: Show export
        run: |
          export OWRT_TARGET=${{inputs.OWRT_TARGET}}
          export OWRT_THEME=${{inputs.OWRT_THEME}}
          export OWRT_NAME=${{inputs.OWRT_NAME}}
          export OWRT_PW=${{inputs.OWRT_PW}}
          export OWRT_IP=${{inputs.OWRT_IP}}
          export OWRT_URL=${{inputs.OWRT_URL}}

          echo "$OWRT_TARGET"
          echo "$OWRT_THEME"
          echo "$OWRT_NAME"
          echo "$OWRT_PW"
          echo "$OWRT_IP"
          echo "$OWRT_URL"

      - name: Clone OWRT Code
        run: |
          git clone --depth=1 --single-branch $OWRT_URL ./owrt

      - name: Package Firmware
        run: |
          export OWRT_TYPE=$(sed -n "1{s/^#//;s/\r$//;p;q}" $GITHUB_WORKSPACE/Config/$OWRT_TARGET.txt)
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")

          echo "OWRT_TARGET=$OWRT_TARGET" >> $GITHUB_ENV
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          echo "OWRT_NAME=$OWRT_NAME" >> $GITHUB_ENV
          echo "OWRT_TYPE=$OWRT_TYPE" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV
          echo "OWRT_PW=$OWRT_PW" >> $GITHUB_ENV

          cd ./owrt && mkdir ./upload
          cp -rf ./.config ./upload/Config_"$OWRT_TARGET"_"$OWRT_NAME"_"$OWRT_DATE".txt

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.OWRT_TARGET}}_${{env.OWRT_NAME}}_${{env.OWRT_DATE}}
          files: ./owrt/upload/*.md
          body: |
            这是个平台固件包，内含多个设备！
            请注意选择你需要的设备固件！
            设备：${{env.OWRT_TYPE}}
            地址：${{env.OWRT_IP}}
            密码：${{env.OWRT_PW}}

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 6
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
